Add beforeUpsertOne hook handling in createDate plugin
2do2go/mongodbext pull request #25
Opened 2021-05-18 07:55 UTC by nazar-i

Register `beforeUpsertOne` hook in `createDate` plugin. In that hook add `createDate` field to `$setOnInsert` modifier if it not present in condition and modifier yet. 
So, `createDate` would be correctly setted when using `findOneAnaUpsert` method with `createDate` plugin.
Fix #18

2021-05-20 12:39 UTC, anton-makarov requested changes

2021-05-20 12:39 UTC, anton-makarov commented on lib/plugins/createDate.js
> +				$set: setters,
This actually breaks behaviour of replaces, because instead of replacing the while document just some fields will be updated. My suggestion is to just add `createDate` to `modifier` without any modification operators because replacing entity is like creating a new one

2021-05-20 12:39 UTC, anton-makarov commented on lib/plugins/createDate.js
> +		if (isModifierEmpty) {
In this case entity will be replaced with condition object. My suggestion is do not use `$setOnInsert` operator because it breaks behaviour and just add `createDate` to `modifier` object

2021-06-02 10:38 UTC, nazar-i commented on lib/plugins/createDate.js
> +				$set: setters,
Oh, I got it... So, I simplified  this condition statements and  `createDate` will be wrapped in  `$setOnInsert` operator only if modifier already has update operators. Added tests for this case too.
Also, is it clear for a user, that if a modifier doesn't have update operator (so findOneAndReplace will be use), fields from the filter will not be presented in finite document?

2021-06-03 08:39 UTC, merged